---
name: abi

on:
  push:
    branches:
      - patches-2.1
      - release-*-pull
    tags:
      - release-*

jobs:
  abi:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.0.0

      - name: Install Dependencies
        run:
          sudo apt install
            abi-tracker
            abi-monitor
            abi-dumper
            abi-compliance-checker
            pkgdiff
            vtable-dumper

      - name: Generate
        shell: bash
        run: |
          ./extra/abi-check/abi_check.sh
        env:
          ABI_CHECK_ROOT: /tmp/le-abi-root

      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: /tmp/le-abi-root/work/abi-check
